#!/usr/bin/env bash
# Build the favicons from the visualisation itself: render one frame of public/index.html with
# huge mosaic tiles and no text, read each tile's colour back from WebGL, and lay the colours
# out as public/favicon.svg. That SVG is then rasterised to public/apple-touch-icon.png (180)
# and public/favicon.ico (32).
# Usage: scripts/make-icons.sh [grid 3..8] [palette] [pattern] [dots|squares] [reveal 0..1] [time s]
# (macOS: uses sips)
set -euo pipefail
cd "$(dirname "$0")/../public"

GRID="${1:-5}"
PALETTE="${2:-dusk}"
PATTERN="${3:-swirl}"
SHAPE="${4:-dots}"
REVEAL="${5:-0.4}"
TIME="${6:-9}"
CHROME="${CHROME:-/Applications/Google Chrome.app/Contents/MacOS/Google Chrome}"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# 1. Sample: a copy of the page that reports the centre colour of each tile after it draws.
TILE=$((512 / GRID))
python3 - "$GRID" "$TILE" index.html "$TMP/sample.html" <<'PY'
import sys
grid, tile, src, dst = int(sys.argv[1]), int(sys.argv[2]), sys.argv[3], sys.argv[4]
probe = f"""<script>
const draw = WebGLRenderingContext.prototype.drawArrays;
WebGLRenderingContext.prototype.drawArrays = function (...a) {{
  draw.apply(this, a);
  const px = new Uint8Array(4), out = [];
  for (let r = {grid} - 1; r >= 0; r--)          // tiles count up from the bottom in GL
    for (let c = 0; c < {grid}; c++) {{
      this.readPixels(Math.floor((c + 0.5) * {tile}), Math.floor((r + 0.5) * {tile}), 1, 1, this.RGBA, this.UNSIGNED_BYTE, px);
      out.push("#" + [...px.slice(0, 3)].map(v => v.toString(16).padStart(2, "0")).join(""));
    }}
  document.title = out.join(",");
}};
</script>"""
s = open(src).read().replace("<head>", "<head>" + probe, 1)
open(dst, "w").write(s)
PY
# (the window is taller than the 512px viewport it yields in headless Chrome)
COLOURS="$("$CHROME" --headless=new --use-angle=swiftshader --enable-unsafe-swiftshader \
  --hide-scrollbars --window-size=512,599 --virtual-time-budget=2500 --dump-dom \
  "file://$TMP/sample.html?still=$REVEAL&t=$TIME&tile=$TILE&palette=$PALETTE&pattern=$PATTERN&tiles=$SHAPE&notext" 2>/dev/null \
  | sed -n 's|.*<title>\([^<]*\)</title>.*|\1|p')"
[ -n "$COLOURS" ] || { echo "could not sample colours" >&2; exit 1; }

# 2. Lay the colours out as a mosaic on the palette's background.
python3 - "$GRID" "$COLOURS" "$PALETTE" "$SHAPE" index.html favicon.svg <<'PY'
import re, sys
grid, cols, palette, shape, page, dst = int(sys.argv[1]), sys.argv[2].split(","), sys.argv[3], sys.argv[4], sys.argv[5], sys.argv[6]
bg = re.search(rf'{palette}:\s*\["(#[0-9a-fA-F]{{6}})"', open(page).read()).group(1)
pad, gap = 1.5, 1.0
cell = (32 - 2 * pad - (grid - 1) * gap) / grid
f = lambda v: f"{v:.3g}"
rects = []
for i, c in enumerate(cols):
    x, y = pad + (i % grid) * (cell + gap), pad + (i // grid) * (cell + gap)
    if shape == "dots":
        # halftone, as in the shader: brighter tiles print bigger dots
        r, g, b = (int(c[k:k + 2], 16) / 255 for k in (1, 3, 5))
        v = min(1.0, (0.35 * r + 0.45 * g + 0.2 * b) * 1.4)
        rad = (cell + gap) * (0.27 + 0.2 * v)
        rects.append(f'  <circle cx="{f(x + cell / 2)}" cy="{f(y + cell / 2)}" r="{f(rad)}" fill="{c}"/>')
    else:
        rects.append(f'  <rect x="{f(x)}" y="{f(y)}" width="{f(cell)}" height="{f(cell)}" rx="0.8" fill="{c}"/>')
svg = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">\n'
       f'  <!-- generated by scripts/make-icons.sh: {grid}×{grid} {shape} sampled from the {palette} moiré -->\n'
       f'  <rect width="32" height="32" rx="6" fill="{bg}"/>\n' + "\n".join(rects) + "\n</svg>\n")
open(dst, "w").write(svg)
PY

# 3. Rasterise. iOS masks touch icons itself, so give it a square, fully opaque background.
sed 's/<rect width="32" height="32" rx="6"/<rect width="32" height="32"/' favicon.svg > "$TMP/square.svg"
sips -s format png -z 180 180 "$TMP/square.svg" --out apple-touch-icon.png >/dev/null
sips -s format png -z 32 32 favicon.svg --out "$TMP/32.png" >/dev/null

# An .ico may hold a PNG directly: 6-byte header + one 16-byte directory entry + the PNG.
python3 - "$TMP/32.png" favicon.ico <<'PY'
import struct, sys
png = open(sys.argv[1], "rb").read()
ico = struct.pack("<HHH", 0, 1, 1) + struct.pack("<BBBBHHII", 32, 32, 0, 0, 1, 32, len(png), 22) + png
open(sys.argv[2], "wb").write(ico)
PY

echo "wrote public/favicon.svg, public/apple-touch-icon.png, public/favicon.ico (grid=$GRID palette=$PALETTE pattern=$PATTERN shape=$SHAPE)"
